// The 100-app research set from the take-home assignment.
// Each entry: id, name, category group, and the doc/website hint URL given in the brief.
// These are the exact apps the assignment asks us to profile. No fabricated entries.

export const APPS = [
  // 1. CRM and Sales
  { id: 1, name: "Salesforce", group: "CRM & Sales", hint: "https://www.salesforce.com/" },
  { id: 2, name: "HubSpot", group: "CRM & Sales", hint: "https://www.hubspot.com/" },
  { id: 3, name: "Pipedrive", group: "CRM & Sales", hint: "https://www.pipedrive.com/" },
  { id: 4, name: "Attio", group: "CRM & Sales", hint: "https://attio.com/" },
  { id: 5, name: "Twenty", group: "CRM & Sales", hint: "https://twenty.com/" },
  { id: 6, name: "Podio", group: "CRM & Sales", hint: "https://podio.com/" },
  { id: 7, name: "Zoho CRM", group: "CRM & Sales", hint: "https://www.zoho.com/crm/" },
  { id: 8, name: "Close", group: "CRM & Sales", hint: "https://close.com/" },
  { id: 9, name: "Copper", group: "CRM & Sales", hint: "https://copper.com/" },
  { id: 10, name: "DealCloud", group: "CRM & Sales", hint: "https://api.docs.dealcloud.com/" },

  // 2. Support and Helpdesk
  { id: 11, name: "Zendesk", group: "Support & Helpdesk", hint: "https://www.zendesk.com/" },
  { id: 12, name: "Intercom", group: "Support & Helpdesk", hint: "https://www.intercom.com/" },
  { id: 13, name: "Freshdesk", group: "Support & Helpdesk", hint: "https://www.freshworks.com/freshdesk/" },
  { id: 14, name: "Front", group: "Support & Helpdesk", hint: "https://front.com/" },
  { id: 15, name: "Pylon", group: "Support & Helpdesk", hint: "https://www.usepylon.com/" },
  { id: 16, name: "LiveAgent", group: "Support & Helpdesk", hint: "https://www.liveagent.com/" },
  { id: 17, name: "Plain", group: "Support & Helpdesk", hint: "https://www.plain.com/" },
  { id: 18, name: "Help Scout", group: "Support & Helpdesk", hint: "https://www.helpscout.com/" },
  { id: 19, name: "Gorgias", group: "Support & Helpdesk", hint: "https://www.gorgias.com/" },
  { id: 20, name: "Gladly", group: "Support & Helpdesk", hint: "https://www.gladly.com/" },

  // 3. Communications and Messaging
  { id: 21, name: "Slack", group: "Comms & Messaging", hint: "https://slack.com/" },
  { id: 22, name: "Twilio", group: "Comms & Messaging", hint: "https://www.twilio.com/" },
  { id: 23, name: "Zoho Cliq", group: "Comms & Messaging", hint: "https://www.zoho.com/cliq/" },
  { id: 24, name: "Lark (Larksuite)", group: "Comms & Messaging", hint: "https://open.larksuite.com/" },
  { id: 25, name: "Pumble", group: "Comms & Messaging", hint: "https://pumble.com/" },
  { id: 26, name: "Discord", group: "Comms & Messaging", hint: "https://discord.com/" },
  { id: 27, name: "Telegram", group: "Comms & Messaging", hint: "https://core.telegram.org/" },
  { id: 28, name: "WhatsApp Business", group: "Comms & Messaging", hint: "https://developers.facebook.com/docs/whatsapp/" },
  { id: 29, name: "Aircall", group: "Comms & Messaging", hint: "https://aircall.io/" },
  { id: 30, name: "Vonage", group: "Comms & Messaging", hint: "https://developer.vonage.com/" },

  // 4. Marketing, Ads, Email and Social
  { id: 31, name: "Google Ads", group: "Marketing & Social", hint: "https://developers.google.com/google-ads/" },
  { id: 32, name: "Meta Ads", group: "Marketing & Social", hint: "https://developers.facebook.com/docs/marketing-apis/" },
  { id: 33, name: "LinkedIn Ads", group: "Marketing & Social", hint: "https://learn.microsoft.com/en-us/linkedin/marketing/" },
  { id: 34, name: "GoHighLevel", group: "Marketing & Social", hint: "https://highlevel.stoplight.io/" },
  { id: 35, name: "Mailchimp", group: "Marketing & Social", hint: "https://mailchimp.com/developer/" },
  { id: 36, name: "Klaviyo", group: "Marketing & Social", hint: "https://developers.klaviyo.com/" },
  { id: 37, name: "systeme.io", group: "Marketing & Social", hint: "https://systeme.io/" },
  { id: 38, name: "Pinterest", group: "Marketing & Social", hint: "https://developers.pinterest.com/" },
  { id: 39, name: "Threads (Meta)", group: "Marketing & Social", hint: "https://developers.facebook.com/docs/threads" },
  { id: 40, name: "SendGrid", group: "Marketing & Social", hint: "https://sendgrid.com/" },

  // 5. Ecommerce
  { id: 41, name: "Shopify", group: "Ecommerce", hint: "https://shopify.dev/" },
  { id: 42, name: "WooCommerce", group: "Ecommerce", hint: "https://woocommerce.com/document/woocommerce-rest-api/" },
  { id: 43, name: "BigCommerce", group: "Ecommerce", hint: "https://developer.bigcommerce.com/" },
  { id: 44, name: "Salesforce Commerce Cloud", group: "Ecommerce", hint: "https://developer.salesforce.com/docs/commerce-cloud" },
  { id: 45, name: "Magento (Adobe Commerce)", group: "Ecommerce", hint: "https://developer.adobe.com/commerce/" },
  { id: 46, name: "Squarespace", group: "Ecommerce", hint: "https://developers.squarespace.com/" },
  { id: 47, name: "Ecwid", group: "Ecommerce", hint: "https://api-docs.ecwid.com/" },
  { id: 48, name: "Gumroad", group: "Ecommerce", hint: "https://gumroad.com/api" },
  { id: 49, name: "Amazon Selling Partner", group: "Ecommerce", hint: "https://developer-docs.amazon.com/sp-api/" },
  { id: 50, name: "fanbasis", group: "Ecommerce", hint: "https://fanbasis.com/" },

  // 6. Data, SEO and Scraping
  { id: 51, name: "DataForSEO", group: "Data, SEO & Scraping", hint: "https://docs.dataforseo.com/" },
  { id: 52, name: "SE Ranking", group: "Data, SEO & Scraping", hint: "https://seranking.com/api.html" },
  { id: 53, name: "Ahrefs", group: "Data, SEO & Scraping", hint: "https://ahrefs.com/api" },
  { id: 54, name: "MrScraper", group: "Data, SEO & Scraping", hint: "https://docs.mrscraper.com/" },
  { id: 55, name: "Apify", group: "Data, SEO & Scraping", hint: "https://docs.apify.com/" },
  { id: 56, name: "Firecrawl", group: "Data, SEO & Scraping", hint: "https://www.firecrawl.dev/" },
  { id: 57, name: "Bright Data", group: "Data, SEO & Scraping", hint: "https://brightdata.com/" },
  { id: 58, name: "Sherlock", group: "Data, SEO & Scraping", hint: "https://github.com/sherlock-project/sherlock" },
  { id: 59, name: "Waterfall.io", group: "Data, SEO & Scraping", hint: "https://waterfall.io/" },
  { id: 60, name: "Clay", group: "Data, SEO & Scraping", hint: "https://www.clay.com/" },

  // 7. Developer, Infra and Data platforms
  { id: 61, name: "GitHub", group: "Dev, Infra & Data", hint: "https://docs.github.com/rest" },
  { id: 62, name: "Vercel", group: "Dev, Infra & Data", hint: "https://vercel.com/docs/rest-api" },
  { id: 63, name: "Netlify", group: "Dev, Infra & Data", hint: "https://docs.netlify.com/api/" },
  { id: 64, name: "Cloudflare", group: "Dev, Infra & Data", hint: "https://developers.cloudflare.com/api/" },
  { id: 65, name: "Supabase", group: "Dev, Infra & Data", hint: "https://supabase.com/docs" },
  { id: 66, name: "Neo4j", group: "Dev, Infra & Data", hint: "https://neo4j.com/docs/api/" },
  { id: 67, name: "Snowflake", group: "Dev, Infra & Data", hint: "https://docs.snowflake.com/" },
  { id: 68, name: "MongoDB Atlas", group: "Dev, Infra & Data", hint: "https://www.mongodb.com/docs/atlas/api/" },
  { id: 69, name: "Datadog", group: "Dev, Infra & Data", hint: "https://docs.datadoghq.com/api/" },
  { id: 70, name: "Sentry", group: "Dev, Infra & Data", hint: "https://docs.sentry.io/api/" },

  // 8. Productivity and Project Management
  { id: 71, name: "Notion", group: "Productivity & PM", hint: "https://developers.notion.com/" },
  { id: 72, name: "Airtable", group: "Productivity & PM", hint: "https://airtable.com/developers" },
  { id: 73, name: "Linear", group: "Productivity & PM", hint: "https://developers.linear.app/" },
  { id: 74, name: "Jira", group: "Productivity & PM", hint: "https://developer.atlassian.com/" },
  { id: 75, name: "Asana", group: "Productivity & PM", hint: "https://developers.asana.com/" },
  { id: 76, name: "Monday.com", group: "Productivity & PM", hint: "https://developer.monday.com/" },
  { id: 77, name: "ClickUp", group: "Productivity & PM", hint: "https://clickup.com/api" },
  { id: 78, name: "Coda", group: "Productivity & PM", hint: "https://coda.io/developers" },
  { id: 79, name: "Smartsheet", group: "Productivity & PM", hint: "https://smartsheet.com/developers" },
  { id: 80, name: "Harvest", group: "Productivity & PM", hint: "https://help.getharvest.com/api-v2/" },

  // 9. Finance and Fintech
  { id: 81, name: "Stripe", group: "Finance & Fintech", hint: "https://stripe.com/docs/api" },
  { id: 82, name: "Plaid", group: "Finance & Fintech", hint: "https://plaid.com/docs/" },
  { id: 83, name: "Binance", group: "Finance & Fintech", hint: "https://binance-docs.github.io/apis/" },
  { id: 84, name: "Paygent Connect", group: "Finance & Fintech", hint: "https://www.paygent.co.jp/" },
  { id: 85, name: "iPayX", group: "Finance & Fintech", hint: "https://ipayx.ai/docs" },
  { id: 86, name: "QuickBooks", group: "Finance & Fintech", hint: "https://developer.intuit.com/" },
  { id: 87, name: "Xero", group: "Finance & Fintech", hint: "https://developer.xero.com/" },
  { id: 88, name: "Brex", group: "Finance & Fintech", hint: "https://developer.brex.com/" },
  { id: 89, name: "Ramp", group: "Finance & Fintech", hint: "https://docs.ramp.com/" },
  { id: 90, name: "PitchBook", group: "Finance & Fintech", hint: "https://pitchbook.com/" },

  // 10. AI, Research and Media-native
  { id: 91, name: "NotebookLM", group: "AI, Research & Media", hint: "https://cloud.google.com/gemini" },
  { id: 92, name: "Otter AI", group: "AI, Research & Media", hint: "https://help.otter.ai/" },
  { id: 93, name: "Fathom", group: "AI, Research & Media", hint: "https://fathom.video/" },
  { id: 94, name: "Consensus", group: "AI, Research & Media", hint: "https://consensus.app/" },
  { id: 95, name: "Reducto", group: "AI, Research & Media", hint: "https://www.reducto.ai/" },
  { id: 96, name: "Devin", group: "AI, Research & Media", hint: "https://docs.devin.ai/" },
  { id: 97, name: "higgsfield", group: "AI, Research & Media", hint: "https://higgsfield.ai/cli" },
  { id: 98, name: "Mermaid CLI", group: "AI, Research & Media", hint: "https://github.com/mermaid-js/mermaid-cli" },
  { id: 99, name: "YouTube Transcript", group: "AI, Research & Media", hint: "https://www.transcriptapi.com/" },
  { id: 100, name: "Grain", group: "AI, Research & Media", hint: "https://grain.com/" }
];

// Map app name -> Composio toolkit slug (best-effort, verified at runtime).
// Used to look up genuine Composio catalog data; unknown => LLM-only path.
export const SLUG_HINTS = {
  "Salesforce": "salesforce",
  "HubSpot": "hubspot",
  "Pipedrive": "pipedrive",
  "Attio": "attio",
  "Twenty": "twenty",
  "Podio": "podio",
  "Zoho CRM": "zohocrm",
  "Close": "close",
  "Copper": "copper",
  "Zendesk": "zendesk",
  "Intercom": "intercom",
  "Freshdesk": "freshdesk",
  "Front": "front",
  "Help Scout": "helpscout",
  "Gorgias": "gorgias",
  "Slack": "slack",
  "Twilio": "twilio",
  "Zoho Cliq": "zohocliq",
  "Lark (Larksuite)": "larksuite",
  "Discord": "discord",
  "Telegram": "telegram",
  "WhatsApp Business": "whatsapp",
  "Aircall": "aircall",
  "Vonage": "vonage",
  "Google Ads": "googleads",
  "Meta Ads": "facebook",
  "LinkedIn Ads": "linkedin",
  "Mailchimp": "mailchimp",
  "Klaviyo": "klaviyo",
  "Pinterest": "pinterest",
  "SendGrid": "sendgrid",
  "Shopify": "shopify",
  "WooCommerce": "woocommerce",
  "BigCommerce": "bigcommerce",
  "Magento (Adobe Commerce)": "magento",
  "Squarespace": "squarespace",
  "Ecwid": "ecwid",
  "Gumroad": "gumroad",
  "Amazon Selling Partner": "amazon",
  "Apify": "apify",
  "Firecrawl": "firecrawl",
  "Bright Data": "brightdata",
  "Clay": "clay",
  "GitHub": "github",
  "Vercel": "vercel",
  "Netlify": "netlify",
  "Cloudflare": "cloudflare",
  "Supabase": "supabase",
  "Neo4j": "neo4j",
  "Snowflake": "snowflake",
  "MongoDB Atlas": "mongodb",
  "Datadog": "datadog",
  "Sentry": "sentry",
  "Notion": "notion",
  "Airtable": "airtable",
  "Linear": "linear",
  "Jira": "jira",
  "Asana": "asana",
  "Monday.com": "monday",
  "ClickUp": "clickup",
  "Coda": "coda",
  "Smartsheet": "smartsheet",
  "Harvest": "harvest",
  "Stripe": "stripe",
  "Plaid": "plaid",
  "Binance": "binance",
  "QuickBooks": "quickbooks",
  "Xero": "xero",
  "Brex": "brex",
  "Ramp": "ramp",
  "NotebookLM": null,
  "Otter AI": "otterai",
  "Consensus": "consensus",
  "Devin": "devin",
  "Grain": "grain"
};
